### ISSUE TITLE
groupVars in branch inputNSD are not applied

### ISSUE THREAD

**Issue by mwelch750** [alexkowa/sdcMicroGUI#1]
Testing inputNSD branch for World Bank (Olivier Dupriez and Matthew Welch):

Attempts to use Anonymisation>recode>group selected variables does not appear to be applied even though an entry is generated in the script log for the recode. No recalculation of risk is done either.
R - 3.2.2. - Windows 7 (64bit) - sdcMicroGUI > inputNSD branch - built from guithub source 27/10/2015

**Comment by thijsbenschop** [comment]
This problem seems to come from using the newest version of sdcMicro (4.6.0). In the groupVars function, the after argument must have the same length as the before argument. This was not the case in the previous version (4.5.0) and therefore, it doesn't work in the GUI now (if newer version is installed). The error message appears in the command line in R: Arguments 'before' and 'after' have different length!

**Comment by bernhard-da** [comment]
Hi, thx for reporting. Could be please try again and report back if the latest commit fixed the issue?

**Comment by mwelch750** [comment]
Hi Bernard,

The issue is indeed resolved.
I did not give you all my platform information. Testing was on Windows 64bit, R3.2.2, sdcMicro 4.6.0 (latest pulled from Github not CRAN).

Thank you for your prompt response.

Best
Matthew

**Comment by bernhard-da** [comment]
@mwelch750 thx for testing this out.
